# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3307/osahaneat
#     username: root
#     password: 5555
#     driver-class-name:
#   jpa:
#     hibernate:
#       ddl-auto: none
spring:
  jpa:
    hibernate:
      entity-manager-factory-name: entityManagerFactory
      entity-manager-factory:
        interface: jakarta.persistence.EntityManagerFactory
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
    show-sql: true
    generate-ddl: true
    hbm2ddl:
      auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/osahaneat
    username: root
    password: 5555
    driver-class-name: com.mysql.cj.jdbc.Driver
  # service:
  #   multipart:
  #     max-file-size: 10MB

jwt:
  privateKey: tjwDPsW0fVam+TBpSQyfzlESYCpCRqTHdKCyPv9deig=

fileUpload:
  rootPath: C:\Users\Admin\Desktop\uploads
# logging:
#   level:
#     root: info
#   file:
#     name: C:\Users\Admin\Desktop\logger\dev.log
